# NPC Data Manager
# Auto-generated by create_npc_registry.sh
extends Node

# NPC registry
var npc_registry = {}

# Load NPC data on ready
func _ready():
    load_npc_data()

# Load NPC data from JSON file
func load_npc_data():
    var file = File.new()
    if file.file_exists("res://data/npc_registry.json"):
        file.open("res://data/npc_registry.json", File.READ)
        var text = file.get_as_text()
        var result = JSON.parse(text)
        file.close()
        if result.error == OK:
            npc_registry = result.result
        else:
            print("Error parsing NPC registry JSON: ", result.error_string)
    else:
        print("NPC registry file not found")

# Save NPC data to JSON file
func save_npc_data():
    var file = File.new()
    file.open("res://data/npc_registry.json", File.WRITE)
    file.store_string(JSON.print(npc_registry, "  "))
    file.close()

# Get an NPC by ID
func get_npc(id):
    for npc in npc_registry.npcs:
        if npc.id == id:
            return npc
    return null

# Set NPC assimilation status
func set_assimilated(id, assimilated):
    var npc = get_npc(id)
    if npc != null:
        npc.assimilated = assimilated
        save_npc_data()
        return true
    return false

# Set NPC suspicious level
func set_suspicious_level(id, level):
    var npc = get_npc(id)
    if npc != null:
        npc.suspicious_level = clamp(level, 0.0, 1.0)
        save_npc_data()
        return true
    return false

# Mark NPC as known assimilated
func set_known_assimilated(id, known):
    var npc = get_npc(id)
    if npc != null:
        npc.known_assimilated = known
        save_npc_data()
        return true
    return false

# Get all assimilated NPCs
func get_assimilated_npcs():
    var result = []
    for npc in npc_registry.npcs:
        if npc.assimilated:
            result.append(npc)
    return result

# Get all known assimilated NPCs
func get_known_assimilated_npcs():
    var result = []
    for npc in npc_registry.npcs:
        if npc.known_assimilated:
            result.append(npc)
    return result

# Get NPCs by location
func get_npcs_by_location(location):
    var result = []
    for npc in npc_registry.npcs:
        if npc.location == location:
            result.append(npc)
    return result

# Get count of assimilated NPCs
func get_assimilated_count():
    var count = 0
    for npc in npc_registry.npcs:
        if npc.assimilated:
            count += 1
    return count

# Get count of known assimilated NPCs
func get_known_assimilated_count():
    var count = 0
    for npc in npc_registry.npcs:
        if npc.known_assimilated:
            count += 1
    return count
